### PR TITLE
Update RemoveOcclusionFromSectors.wscript

### PR DESCRIPTION
**Pull request by notaspirit**
Added:
1. description and usage 
2. Counter for how many nodes and sectors are affected Modified:
1. sectornames for the output file are now shortened by
- 1. changing "exterior" and "interior" to "e" and "i"
- 2. removing "_" within the sector name

### CODE REVIEW

**Comment by manavortex** [comment]
@Simarilius-uk, this might break the Blender plugin again?

**Comment by Simarilius-uk** [comment]
> @Simarilius-uk, this might break the Blender plugin again?

its just a wscript for generating axl deletion lists, dont see how it would affect the plugin.

**Comment by notaspirit** [comment]
does anything need to be adjusted, or is there a different reason for it still being open?

**Comment by manavortex** [comment]
I forgot

**Pull request merged**
